# Tolaria configuration for tech demo
# Training parameters
learning_rate: 0.001
weight_decay: 0.0001
max_epochs: 50

# Optimizer settings
optimizer: "adam"
scheduler: "cosine"
scheduler_params:
  eta_min: 0.00001

# Morphogenetic settings
tamiyo_policy_path: null
adaptation_frequency: 5
max_adaptations_per_epoch: 2
adaptation_cooldown: 30

# Model configuration
model:
  architecture: "resnet18"
  num_classes: 10
  pretrained: false
  target_layers: ["nn.Linear", "nn.Conv2d"]
  seeds_per_layer: 4
  seed_cache_size_mb: 256
  model_params:
    dropout_rate: 0.1

# Dataset configuration
dataset:
  name: "cifar10"
  data_dir: "./data"
  download: true
  batch_size: 64
  num_workers: 2
  pin_memory: true
  val_split: 0.1
  train_transforms:
    random_crop: 32
    random_flip: true
    normalize: true
  val_transforms:
    normalize: true

# Infrastructure configuration
oona:
  url: "http://tamiyo:8001"
  timeout: 30.0

urza:
  base_url: "http://urza:8000"
  timeout: 30.0
  retry_attempts: 3

# Checkpointing and logging
checkpoint_dir: "/app/checkpoints"
checkpoint_frequency: 10
log_frequency: 100

# Device and performance
device: "cuda"
mixed_precision: true
compile_model: false  # Disable for demo to speed up startup

# Experiment tracking
experiment_name: "esper_demo_morphogenetic"
experiment_tags: ["demo", "morphogenetic", "cifar10"]