apiVersion: v1
kind: Secret
metadata:
  name: esper-secrets
  namespace: esper
  labels:
    app.kubernetes.io/name: esper
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # These should be replaced with actual secure values in production
  postgres-password: "CHANGE_ME_SECURE_POSTGRES_PASSWORD"
  redis-password: "CHANGE_ME_SECURE_REDIS_PASSWORD"
  minio-access-key: "CHANGE_ME_MINIO_ACCESS_KEY"
  minio-secret-key: "CHANGE_ME_MINIO_SECRET_KEY"